// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqlffsqphgdqxzmrqwfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxbGZmc3FwaGdkcXh6bXJxd2Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4MjgxOTAsImV4cCI6MjA4OTQwNDE5MH0.Y92Zl4j3hc60HGegwc2PXoxyAzbQVhA2Sq9EO9CzNMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});